name: SpellCheck

on: workflow_call

permissions:
  contents: read

jobs:
    build:
        name: Run spell check
        runs-on: ubuntu-latest
        steps:
            - name: Harden Runner
              uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142 # v2.7.0
              with:
                egress-policy: audit

            - name: Checkout
              uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

            - name: Run a spell check
              uses: crate-ci/typos@c97d621b6b01d8b0258538ca15abeca5c5764601 # v1.16.23
              with:
                config: ./.github/workflows/.spellcheck-conf.toml
